Update iget.yml
Signed-off-by: BBX19 <xizzix19@gmail.com>

diff --git a/.github/workflows/iget.yml b/.github/workflows/iget.yml
--- a/.github/workflows/iget.yml
+++ b/.github/workflows/iget.yml
@@ -21,12 +21,8 @@ jobs:
         run: pip install requests
 
       - name: Run IGET
-  run: |
-    python iget/main.py > result.txt || echo "IGET ERROR" > result.txt
-  env:
-    PR_NUMBER: ${{ github.event.pull_request.number }}
-    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      " > result.txt
+        run: |
+          python iget/main.py > result.txt || echo "IGET ERROR" > result.txt
         env:
           PR_NUMBER: ${{ github.event.pull_request.number }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
